// src/frontend/App.vue
<script setup lang="ts">
import { ref, computed } from 'vue';

import { Parser, Grammar } from 'nearley';
import grammar from "../backend/conversion/parsing/grammar";

const compiledGrammar = Grammar.fromCompiled(grammar);

const input = ref(``);
const result = computed(() => {
  try {
    const result = new Parser(compiledGrammar).feed(input.value).results[0];
    return {
      success: true,
      value: result,
      display: JSON.stringify(result, null, 2),
    };
  } catch (e: any) {
    // eslint-disable-next-line no-console
    console.error(e);
    return {
      success: false,
      value: e,
      display: e.toString(),
    };
  }
})
</script>

<template>
  <input type="text" v-model.trim="input" />
  <pre :class="{ err: !result.success }">{{
    result.display
  }}</pre>
</template>

<style scoped>
.err {
  color: red;
}
</style>

// src/frontend/App.tsx
import {createEffect, type Component, createSignal, createRenderEffect, Setter, ErrorBoundary} from 'solid-js';

import {Parser, Grammar} from "nearley";
import styles from './App.module.css';

import grammar from "../backend/conversion/parsing/grammar";

const compiledGrammar = Grammar.fromCompiled(grammar);

declare module "solid-js" {
  namespace JSX {
    // this sucks
    interface Directives {
      bind: [Accessor<string>, Setter<string>];
    }
  }
}

function bind(el: HTMLInputElement, accessor: typeof createSignal<string>) {
  const [s, set] = accessor(``);
  el.addEventListener(`input`, e => set((e.currentTarget as HTMLInputElement).value));
  createRenderEffect(() => {
    el.value = s();
  });
}

function parse(input: string) {
  try {
    return {
      success: true,
      value: JSON.stringify(new Parser(compiledGrammar).feed(input).results, null, 2),
    };
  } catch (e: any) {
    // eslint-disable-next-line no-console
    console.error(e);
    return {
      success: false,
      value: e.toString(),
    };
  }
}

const App: Component = () => {
  const [input, setInput] = createSignal(``);
  const result = () => parse(input());
  return <div>
    <input type="text" use:bind={[input, setInput]}></input>
    <pre style={{color: result().success ? undefined : `red`}}>{result().value}</pre>
  </div>;
};

export default App;
