// src/frontend/App.vue
<script setup lang="ts">
import { ref, computed } from 'vue';

import { Parser, Grammar } from 'nearley';
import grammar from "../backend/conversion/parsing/grammar";

const compiledGrammar = Grammar.fromCompiled(grammar);

const input = ref(``);
const result = computed(() => {
  try {
    const result = new Parser(compiledGrammar).feed(input.value).results[0];
    return {
      success: true,
      value: result,
      display: JSON.stringify(result, null, 2),
    };
  } catch (e: any) {
    // eslint-disable-next-line no-console
    console.error(e);
    return {
      success: false,
      value: e,
      display: e.toString(),
    };
  }
})
</script>

<template>
  <input type="text" v-model.trim="input" />
  <pre :class="{ err: !result.success }">{{
    result.display
  }}</pre>
</template>

<style scoped>
.err {
  color: red;
}
</style>

// src/App.svelte
<script>
    import {Parser, Grammar} from 'nearley';
    import * as grammar from './backend/conversion/parsing/grammar.js';

	const compiledGrammar = Grammar.fromCompiled(grammar);

    let input = ``;
	let res = [];
	let err = ``;

	$: try {
		res = new Parser(compiledGrammar).feed(input).results;
		err = ``;
	} catch (e) {
		err = e;
		console.error(e);
	};
    
</script>

<main>
    <h1>Getting there...</h1>
	<input type="text" bind:value={input} />
	<p>{res.length}</p>

	{#if err}
		<pre style="color:red;" i>{err}</pre>
	{:else}
    	<pre>{JSON.stringify(res, null, 2)}</pre>
	{/if}
</main>

<style>
	main {
		text-align: center;
		padding: 1em;
		max-width: 240px;
		margin: 0 auto;
	}

	pre {
		text-align: left;
	}

	h1 {
		color: #ff3e00;
		/* text-transform: uppercase; */
		font-size: 4em;
		font-weight: 100;
	}

	@media (min-width: 640px) {
		main {
			max-width: none;
		}
	}
</style>
